# Generated by Django 4.1.6 on 2023-08-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
